name: Build RenderEngine To WASM

on:
  push:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 列举项目结构
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    # 3. 安装 Rust 工具链
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        override: true

    # 4. 安装 wasm-pack
    - name: Install wasm-pack
      run: cargo install wasm-pack

    # 5. 构建 Rust 项目为 WASM
    - name: Build WASM with wasm-pack
      run: wasm-pack build --target web --out-dir ./pkg --out-name wgpu-wasm

    # 6. 上传到 artifacts
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-files
        path: ./pkg

  deploy-gh-pages:
    needs: build-wasm
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 切换分支到 gh-pages
      - name: Switch to gh-pages branch
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
          git checkout gh-pages || git checkout --orphan gh-pages

      # 3. 清理旧文件夹
      - name: Remove old files
        run: |
          mkdir -p js
          rm -rf js/*

      # 4. 列出 Artifacts 的文件
      - name: List available artifacts
        run: |
          echo 'Available artifacts:'
          ls $GITHUB_WORKSPACE

      # 5. 下载 WASM 文件
      - name: Download WASM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-files
          path: ./js

      # 6. 打印文件列表
      - name: Display artifact files
        run: |
          echo "Artifact files:"
          ls ./js

      # 7. 提交到 gh-pages
      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin gh-pages
          git add js
          git commit -m "Update WASM files" || echo "No changes to commit"
          git push origin gh-pages