name: Build WGPU To WASM

on:
  push:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 列举项目结构
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    # 3. 安装 Rust 工具链
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        override: true

    # 4. 安装 wasm-pack
    - name: Install wasm-pack
      run: cargo install wasm-pack

    # 5. 构建 Rust 项目为 WASM
    - name: Build WASM with wasm-pack
      run: wasm-pack build --target web --out-dir ./pkg --out-name wgpu-wasm

    # 6. 上传到 artifacts
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-files
        path: ./pkg