name: Build WGPU To WASM

on:
  push:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 列举项目结构
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    # 3. 安装 Rust 工具链
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        override: true

    # 4. 安装 wasm-pack
    - name: Install wasm-pack
      run: cargo install wasm-pack

    # 5. 构建 Rust 项目为 WASM
    - name: Build with wasm-pack
      run: wasm-pack build --target web --out-dir ./wgpu_html/public/js --out-name wgpu-wasm

    # 6. 设置 Node.js 环境
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # 7. 安装 React 依赖
    - name: Install dependencies
      working-directory: ./wgpu_html
      run: npm install

    # 8. 构建 React 项目
    - name: Build React app
      working-directory: ./wgpu_html
      run: npm run build

    # 9. 部署到 Github Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./wgpu_html/build