name: Build WGPU To WASM

on:
  push:
    branches:
      - main

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 Rust 工具链
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      # 3. 安装 wasm-pack
      - name: Install wasm-pack
        run: cargo install wasm-pack

      # 4. 构建 Rust 项目为 WASM
      - name: Build with wasm-pack
        run: wasm-pack build --target web --out-dir ./wgpu_html/public/js --out-name wgpu-wasm

      # 5. 设置 Node.js 环境
      - name: Set up Node.js
        working-directory: ./wgpu_html
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 6. 安装 React 依赖
      - name: Install dependencies
        working-directory: ./wgpu_html
        run: npm install

      # 7. 构建 React 项目
      - name: Build React app
        working-directory: ./wgpu_html
        run: npm run build

      # 8. 部署到 Github Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wgpu_html/build