#name: Deploy to Github Pages
#
#on:
#  workflow_run:
#    workflows: ["Build RenderEngine To WASM"]
#    types:
#      - completed
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      # 1. 检出代码
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      # 2. 切换分支到 gh-pages
#      - name: Switch to gh-pages branch
#        run: |
#          git config user.name "Github Actions"
#          git config user.email "actions@github.com"
#          git checkout gh-pages || git checkout --orphan gh-pages
#
#      # 3. 清理旧文件夹
#      - name: Remove old files
#        run: |
#          mkdir -p js
#          rm -rf js/*
#
#      # 4. 列出 Artifacts 的文件
#      - name: List available artifacts
#        run: |
#          echo 'Available artifacts:'
#          ls $GITHUB_WORKSPACE
#
#      # 4. 下载 WASM 文件
#      - name: Download WASM Artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: wasm-files
#          path: ./js
#
#      # 5. 提交到 gh-pages
#      - name: Commit and Push changes
#        run: |
#          git add js
#          git commit -m "Update WASM files"
#          git push origin gh-pages --force